global_column_names:
  asset_returns_col: "asset_returns"
  symbol_col: "symbol"
  date_col: "date"
  mkt_cap_col: "market_cap"

model_estimation:
  winsor_factor: 0.02
  residualize_styles: false
  mkt_factor_col: "market"
  res_ret_col: "res_asset_returns"
  top_n_mkt_caps: 2000
  mkt_cap_smooth_window: 20

style_factors:
  mom:
    enabled: true
    trailing_days: 252
    half_life: 126
    lag: 20
    winsor_factor: 0.01
    center: true
    standardize: true
    score_col: "mom_score"
  sze:
    enabled: true
    lower_decile: null
    upper_decile: null
    center: true
    standardize: true
    score_col: "sze_score"
  val:
    enabled: true
    winsor_factor: null
    center: true
    standardize: true
    bp_col: "book_price"
    sp_col: "sales_price"
    cf_col: "cf_price"
    score_col: "val_score"